version: '3.8'

services:
  web-fe:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - counter-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    networks:
      - counter-net

networks:
  counter-net:

volumes:
  redis-data:
